//Games phrases
//Challenges game's phrases, they're taken from here if there is no connection.
export const gameChallenges=[
    {hot:1,text:'haz el pino durante un minuto'},
    {hot:1,text:'bésale el pie al jugador de enfrente'},
    {hot:1,text:'termina el vaso'},
    {hot:1,text:'dile a un jugador que se termine su vaso'},
    {hot:1,text:'termínate el vaso del jugador de tu izquierda'},
    {hot:1,text:'háblale a la primera persona desconocida que te mire'},
    {hot:1,text:'tómate un chupito de sabor fuerte y haz como si nada'},
    {hot:1,text:'prepara cuatro chupitos: dos de agua, y dos de alcohol blanco (ginebra por ejemplo). Elige a un jugador, y al azar, los dos bebéis dos chupitos de esos cuatro'},
    {hot:1,text:'déjale tu móvil desbloqueado durante cinco minutos a la persona de tu izquierda'},
    {hot:1,text:'no uses tu móvil durante veinte minutos'},
    {hot:3,text:'escoge una persona: la de tu izquierda, la de tu derecha, o la de enfrente, y líate con ella'},
    {hot:1,text:'quédate de pie durante las próximas diez preguntas'},
    {hot:1,text:'imita a una gallina por diez segundos'},
    {hot:1,text:'escoge a un jugador, que hará los próximos tres retos (aunque aparezca otro nombre de jugador)'},
    {hot:2,text:'cambia una prenda de ropa tuya (no valen complementos) con el jugador de enfrente'},
    {hot:1,text:'estate abrazado durante tres minutos al jugador de la frase anterior'},
    {hot:1,text:'elige a un jugador, para que haga el reto anterior'},
    {hot:1,text:'haz "bottle-flip-challenge". Si lo consigues en dos intentos o menos, todos los jugadores menos tú beben dos chupitos, si no, bebes la cantidad de intentos que hagas hasta conseguirlo'},
    {hot:1,text:'cada vez que aplaudas los demás tienen que seguirte. Quien no lo haga, bebe'},
    {hot:1,text:'juega al juego "bebida aleatoria". La que te toque, la tienes que beber'},
    {hot:1,text:'el jugador que quieras juega y bebe la bebida que salga en "bebida aleatoria"'},
    {hot:1,text:'tararea una canción, quien la adivine manda beber. Si nadie la adivina, bebes'},
    {hot:1,text:'empieza a cantar una canción, si el de tu derecha no la sigue, bebéis los dos'},
    {hot:1,text:'cambia tu bebida con el jugador de enfrente'},
    {hot:1,text:'elige una persona para que se siente encima tuyo durante cinco minutos'},
    {hot:1,text:'elige una persona, y te tienes que sentar encima suyo'},
    {hot:1,text:'durante dos minutos, tienes que repetir la última palabra que diga cada jugador en sus frases'},
    {hot:1,text:'imita todos los movimientos del jugador del anterior reto durante 2 minutos'},
    {hot:1,text:'haz diez flexiones'},
    {hot:1,text:'los dos jugadores a tu lado hacen diez flexiones. Quien tarde más bebe 3 tragos'},
    {hot:1,text:'los cuatro jugadores más cercanos a ti y tú os levantais. El más alto reparte 5 tragos entre vosotros'},
    {hot:1,text:'todos los jugadores te cantan el cumpleaños feliz. ¡Feliz cumpleaños!'},
    {hot:1,text:'llama a un familiar y dile que le quieres mucho'},
    {hot:1,text:'menciona a la persona que mejor y peor te caen, pero sin decir quién es quién'},
    {hot:1,text:'di una cualidad buena y otra mala sobre la persona del reto anterior'},
    {hot:1,text:'si tienes más de 50 % de batería, bebes 5 tragos. Si no, los repartes'},
    {hot:1,text:'invita a jugar a alguien desconocido'},
    {hot:1,text:'publica una encuesta en instagram con algo que te pueda dejar en evidencia (si creen que eres guapo o feo…)'},
    {hot:2,text:'tócale el culo al jugador que esté dos posiciones a tu izquierda, y que el jugador dos posiciones a tu derecha te lo toque a ti'},
]

export const gameWhowould = [
    {text: 'que sea un adicto al juego'},
    {text: 'que se crea una historia de fantasmas'},
    {text: 'que hiera a alguien físicamente sin querer'},
    {text: 'que se caiga por andar con el móvil'},
    {text: 'que se caiga por despistado'},
    {text: 'que se vaya a vivir a una isla desierta'},
    {text: 'que se quede en paro'},
    {text: 'que tenga alucinaciones'},
    {text: 'que gane una carrera a Usain Bolt'},
    {text: 'que haga trampas en un juego'},
    {text: 'que se haga stripper'},
    {text: 'que le detengan esta noche'},
    {text: 'que se ahogue pensando que sabía nadar'},
    {text: 'que le asuste un animal'},
    {text: 'que se vicie a un juego de móvil'},
    {text: 'que se vea una serie en menos de un día'},
    {text: 'que deje de usar su smartphone durante un tiempo'},
    {text: 'que ligue hoy'},
    {text: 'que no ligue en el próximo año'},
    {text: 'que sea un actor famoso'},
    {text: 'que sea un deportista famoso'},
    {text: 'que llore con una película de risa'},
    {text: 'que disfrute con un dramón'},
    {text: 'que haga el spagat'},
    {text: 'que se rompa un hueso haciendo deporte'},
    {text: 'que no se declare a alguien'},
    {text: 'que vote a VOX'},
    {text: 'que saque un 10 en historia'},
    {text: 'que saque un 10 en matemáticas'},
    {text: 'que disfrute con las clases de filosofía'},
    {text: 'que gane una partida a cartas en cualquier juego'},
    {text: 'que se le den mal los juegos de cartas'},
    {text: 'que se meta a policía'},
    {text: 'que gane Los Juegos del Hambre'},
    {text: 'que se duerma en medio de una fiesta'},
    {text: 'que sea el más bailarín de una fiesta'},
    {text: 'que se convierta en mago y vaya a Hogwarts'},
]
